"""
PHASE 6 - before/after validation report for the code-review fixes.

Reads the AFTER-fix backtest artifacts (per-strategy *_summary.json written by
run_backtest.py, plus the SMC out-of-sample walk-forward report from
walk_forward_oos.py) and writes a markdown comparison against the documented
BEFORE-fix baseline. Applies the deployability gate: a strategy is NOT
deployable if its out-of-sample profit factor is below 1.2 (or if it has no OOS
evidence at all).

This is a pure reporting step -- no trading logic. It does NOT run backtests;
run those first on the VPS (see the runbook in the module docstring of
walk_forward_oos.py and the README block below), then run this.

Run on the VPS after the backtests:
    python scripts/gen_review_report.py
    python scripts/gen_review_report.py --backtests-dir data/backtests

Output:
    data/backtests/review_fixes_report.md
"""
from __future__ import annotations

import argparse
import glob
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent.parent

OOS_PF_MIN = 1.2   # deployability gate: OOS profit factor must clear this

# BEFORE-fix baseline (source: CLAUDE.md "Strategies tested" table + decisions
# log). These predate the swap/short-spread cost fix and the OOS methodology,
# so they are optimistic and in-sample -- exactly what the AFTER numbers test.
BASELINE = {
    "breakout":        {"trades": 322, "pf": 1.04,  "net_pnl_pct": 5.5,    "note": "walk-forward 2/9 positive - dead"},
    "smc":             {"trades": 185, "pf": 1.89,  "net_pnl_pct": 381.0,  "note": "aggressive_all, IN-SAMPLE (params swept on same history)"},
    "mean_reversion":  {"trades": 419, "pf": 0.58,  "net_pnl_pct": -70.16, "note": "aggressive variant - catastrophic"},
    "liquidity_sweep": {"trades": 241, "pf": 0.88,  "net_pnl_pct": -17.4,  "note": "negative edge"},
}


def _pf_to_float(v):
    if v in ("inf", None):
        return float("inf") if v == "inf" else None
    try:
        return float(v)
    except (TypeError, ValueError):
        return None


def _latest_summaries(bt_dir: Path) -> dict:
    """Most-recent *_summary.json per strategy (by filename sort = timestamp)."""
    out = {}
    for path in sorted(glob.glob(str(bt_dir / "*_summary.json"))):
        try:
            d = json.load(open(path))
        except Exception:
            continue
        strat = d.get("strategy")
        if strat:
            out[strat] = d        # later (newer) file wins
    return out


def _load_oos(bt_dir: Path) -> dict | None:
    p = bt_dir / "walk_forward_oos_report.json"
    if not p.exists():
        return None
    try:
        return json.load(open(p))
    except Exception:
        return None


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--backtests-dir", default=str(HERE / "data" / "backtests"))
    ap.add_argument("--out", default=None)
    args = ap.parse_args()

    bt_dir = Path(args.backtests_dir)
    after = _latest_summaries(bt_dir)
    oos = _load_oos(bt_dir)
    out_path = Path(args.out) if args.out else bt_dir / "review_fixes_report.md"

    oos_pf = None
    oos_block = None
    if oos:
        oos_block = oos.get("out_of_sample_overall", {})
        oos_pf = _pf_to_float(oos_block.get("profit_factor"))

    L = []
    L.append("# Code-review fixes - before/after validation\n")
    L.append("Generated by `scripts/gen_review_report.py`. BEFORE = documented "
             "pre-fix baseline (CLAUDE.md). AFTER = backtests re-run with the "
             "fixed cost model (overnight swap + short-side exit spread) and, for "
             "SMC, the out-of-sample walk-forward.\n")
    if not after:
        L.append("\n> **No AFTER-fix `*_summary.json` found in "
                 f"`{bt_dir}`.** Run the backtests first (see runbook below), "
                 "then re-run this generator.\n")

    L.append("\n## What changed\n")
    L.append("- **P1** live bots fetch completed bars (`start_pos=1`), matching the backtest.\n")
    L.append("- **P2** backtest now charges overnight swap and makes shorts pay the exit spread.\n")
    L.append("- **P3** new out-of-sample walk-forward (`walk_forward_oos.py`).\n")
    L.append("- **P4** chop->SMC regime weight reverted 1.0 -> 0.0.\n")
    L.append("- **P5** FVG mitigation check, calendar-aligned MR pivots, conservative MR defaults, dead scaffold deleted.\n")

    # ---- per-strategy table ----
    L.append("\n## Per-strategy: BEFORE vs AFTER\n")
    L.append("| Strategy | BEFORE PF | AFTER PF (full bt) | OOS PF | AFTER PnL% | AFTER trades | Deployable? |")
    L.append("|---|---|---|---|---|---|---|")
    strategies = sorted(set(list(BASELINE.keys()) + list(after.keys())))
    verdicts = {}
    for s in strategies:
        b = BASELINE.get(s, {})
        a = after.get(s, {})
        am = a.get("metrics", {}) if a else {}
        b_pf = b.get("pf", "-")
        a_pf = _pf_to_float(am.get("profit_factor")) if am else None
        a_pf_s = "-" if a_pf is None else ("inf" if a_pf == float("inf") else f"{a_pf:.2f}")
        a_pnl = am.get("net_pnl_pct", "-") if am else "-"
        a_tr = am.get("trades", "-") if am else "-"

        # deployability: gate on OOS PF where available (currently SMC only)
        if s == "smc" and oos_pf is not None:
            this_oos = f"{oos_pf:.2f}"
            deployable = oos_pf >= OOS_PF_MIN
            verdict = "YES" if deployable else f"NO (OOS PF < {OOS_PF_MIN})"
        else:
            this_oos = "-"
            # no OOS evidence -> not deployable regardless of in-sample PF
            verdict = "NO (no OOS run)"
            deployable = False
        verdicts[s] = (verdict, deployable)
        L.append(f"| {s} | {b_pf} | {a_pf_s} | {this_oos} | {a_pnl} | {a_tr} | {verdict} |")

    # ---- OOS detail ----
    if oos:
        cfg = oos.get("config", {})
        L.append("\n## SMC out-of-sample walk-forward\n")
        L.append(f"- windows: {oos.get('n_windows')}  "
                 f"(train {cfg.get('train_months')}mo / test {cfg.get('test_months')}mo, "
                 f"select by {cfg.get('select_metric')})\n")
        L.append(f"- positive OOS windows: {oos.get('positive_oos_windows')}/{oos.get('n_windows')}\n")
        L.append(f"- IN-SAMPLE total R: {oos.get('in_sample_total_r')}  vs  "
                 f"OUT-OF-SAMPLE total R: {oos_block.get('total_r')}\n")
        L.append(f"- OOS profit factor: **{oos_block.get('profit_factor')}**  "
                 f"(gate: >= {OOS_PF_MIN})\n")
        L.append(f"- OOS win rate: {oos_block.get('win_rate')}  "
                 f"max DD: {oos_block.get('max_dd_r')}R  "
                 f"avg R/trade: {oos_block.get('avg_r')}\n")
    else:
        L.append("\n## SMC out-of-sample walk-forward\n")
        L.append("> Not found (`walk_forward_oos_report.json`). Run "
                 "`scripts/walk_forward_oos.py` on the VPS to populate this.\n")

    # ---- verdict ----
    L.append("\n## Deployability verdict\n")
    not_dep = [s for s, (_, ok) in verdicts.items() if not ok]
    dep = [s for s, (_, ok) in verdicts.items() if ok]
    if dep:
        L.append(f"- **Deployable** (OOS PF >= {OOS_PF_MIN}): {', '.join(dep)}\n")
    if not_dep:
        L.append(f"- **NOT deployable**: {', '.join(not_dep)}\n")
    L.append("\n_A strategy is deployable only with out-of-sample profit factor "
             f">= {OOS_PF_MIN}. Strategies without an OOS run are treated as not "
             "deployable until one is produced._\n")

    # ---- runbook ----
    L.append("\n## Runbook (VPS) to (re)generate the AFTER numbers\n")
    L.append("```powershell\n"
             "cd C:\\ai-trading-bot\n"
             "git pull\n"
             "python scripts\\fetch_mt5_history.py            # refresh specs incl. real swap rates\n"
             "python scripts\\run_backtest.py --strategy all --years 4 --equity 960 --risk-pct 0.02\n"
             "python scripts\\sweep_smc.py --years 4\n"
             "python scripts\\walk_forward_oos.py --train-months 12 --test-months 6\n"
             "python scripts\\gen_review_report.py\n"
             "```\n")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(L))
    print(f"Wrote {out_path}")
    print(f"  strategies: {strategies}")
    print(f"  AFTER summaries found: {sorted(after.keys()) or 'NONE'}")
    print(f"  OOS report: {'yes' if oos else 'MISSING'}")
    if not_dep:
        print(f"  NOT deployable: {not_dep}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
